"""Définitions intégrées au glossaire commun, en français et en anglais."""
AIDES = {
    'matrice_destinee': ('Matrice de destinée', 'Destiny matrix',
        "Une lecture symbolique de la date de naissance à travers les 22 arcanes majeurs. Les cinq points A à E sont calculés sans heure ni lieu. On additionne les chiffres tant qu'un résultat dépasse 22 : par exemple 29 devient 11. Le dessin organise ces repères ; il ne prédit pas l'avenir.",
        'A symbolic reading of the birth date through the 22 major arcana. Points A–E need neither time nor place. Digits are added while a result exceeds 22: for example, 29 becomes 11. The drawing organizes these reference points; it does not predict the future.'),
    'matrice_A': ('A · Portrait / jour', 'A · Portrait / day',
        "Le jour de naissance, réduit si nécessaire. Il sert de point d'entrée à la lecture : la manière d'aborder le monde. Exemple : le 5 donne l'arcane 5, Le Pape, associé ici à la transmission et aux repères.",
        'The birth day, reduced if necessary. An entry point to the reading: how one approaches the world. The 5th gives arcana 5, The Hierophant, associated here with teaching and shared values.'),
    'matrice_B': ('B · Spiritualité / mois', 'B · Spirituality / month',
        "Le mois de naissance (1 à 12). Ce repère invite à explorer le sens, les valeurs et les aspirations. Septembre donne 9, L'Hermite : recul et recherche. Ce n'est pas une mesure de spiritualité.",
        'The birth month (1–12). A prompt to explore meaning, values and aspirations. September gives 9, The Hermit: reflection and inquiry. It is not a measure of spirituality.'),
    'matrice_C': ('C · Matière / année', 'C · Matter / year',
        "La somme des chiffres de l'année, réduite jusqu'à 22 au maximum. Pour 1990 : 1+9+9+0 = 19. Ce point propose une réflexion sur la concrétisation et les ressources, sans annoncer une situation matérielle.",
        'The sum of the year’s digits, reduced to no more than 22. For 1990: 1+9+9+0 = 19. This point prompts reflection on realization and resources without predicting material circumstances.'),
    'matrice_D': ('D · Karma de l’âme', 'D · Soul karma',
        "La réduction de A+B+C. Le mot karma désigne ici un thème symbolique d'apprentissage et de répétition, pas une dette réelle ni la preuve d'une vie passée. Pour 5+9+19 = 33, on obtient 6.",
        'The reduction of A+B+C. Karma here means a symbolic theme of learning and recurring patterns, not a real debt or proof of a past life. 5+9+19 = 33 reduces to 6.'),
    'matrice_E': ('E · Centre / zone de confort', 'E · Centre / comfort zone',
        "La réduction de A+B+C+D. Le centre relie les quatre autres points et suggère une manière familière de retrouver ses repères. Pour 5+9+19+6 = 39, le centre est 12, Le Pendu : pause et changement de regard.",
        'The reduction of A+B+C+D. The centre connects the four other points and suggests a familiar way to regain one’s bearings. 5+9+19+6 = 39 gives 12, The Hanged Man: pause and a different perspective.'),
    'matrice_personnel': ('Axe personnel A–D', 'Personal axis A–D',
        "Relie le portrait (A) au thème d'apprentissage (D). Les mots ciel/esprit sont des images pour lire ensemble l'élan personnel et les ajustements. La ligne n'ajoute aucun nombre au calcul.",
        'Connects the portrait (A) to the learning theme (D). Sky/spirit are images for reading personal drive and adjustments together. The line adds no extra number.'),
    'matrice_genealogique': ('Axe généalogique B–C', 'Ancestral axis B–C',
        "Relie spiritualité (B) et matière (C). Il invite à réfléchir aux valeurs transmises et à leur place dans la vie concrète. Il ne révèle ni faits familiaux cachés ni héritage génétique.",
        'Connects spirituality (B) and matter (C). A prompt to reflect on inherited values and their place in everyday life. It reveals neither hidden family facts nor genetic inheritance.'),
    'matrice_finances': ('Canal des finances E–C', 'Resources channel E–C',
        "Un axe symbolique entre la zone de confort et la matière : comment envisager ses ressources, ses choix et sa façon de concrétiser. Aucun score de richesse ni conseil d'investissement n'est calculé.",
        'A symbolic axis between comfort zone and matter: a way to consider resources, choices and realization. No wealth score or investment advice is calculated.'),
    'matrice_amour': ('Canal de l’amour E–D', 'Love channel E–D',
        "Un axe symbolique entre la zone de confort et l'apprentissage : une invitation à réfléchir aux habitudes relationnelles. Il ne mesure pas la compatibilité et ne prédit pas une rencontre.",
        'A symbolic axis between comfort zone and learning: an invitation to reflect on relationship habits. It neither measures compatibility nor predicts an encounter.'),
    'bazi': ('BaZi · quatre piliers', 'BaZi · four pillars',
        "Une tradition chinoise qui représente l'année, le mois, le jour et l'heure par quatre couples : une tige céleste et une branche terrestre, soit huit signes. Le maître du jour est la tige du jour. Les mois suivent des repères solaires ; l'heure civile et le fuseau historique comptent.",
        'A Chinese tradition representing year, month, day and hour as four pairs: a heavenly stem and an earthly branch, making eight signs. The day master is the day stem. Months follow solar markers; civil time and historical timezone matter.'),
    'bazi_piliers': ('Les quatre piliers', 'The four pillars',
        "Chaque colonne correspond à une échelle de temps : année, mois, jour, heure. Le premier caractère est la tige, le second la branche. Leur association fournit un repère symbolique, pas une propriété mesurée de la personne.",
        'Each column represents a timescale: year, month, day, hour. The first character is the stem and the second the branch. Their combination is a symbolic reference, not a measured personal property.'),
    'bazi_maitre': ('Maître du jour', 'Day master',
        "La tige céleste du jour de naissance sert de centre de lecture du BaZi. Elle associe un élément et une polarité, par exemple Eau Yin (Gui). Ce repère est différent de l'élément du signe chinois annuel.",
        'The heavenly stem of the birth day is the centre of the BaZi reading. It combines an element and a polarity, such as Yin Water (Gui). This differs from the element of the annual Chinese sign.'),
    'bazi_elements': ('Les cinq éléments du BaZi', 'Five BaZi elements',
        "Bois, Feu, Terre, Métal, Eau : cinq catégories symboliques. Ici on compte les huit tiges et branches visibles. Un total plus élevé signifie plus de présences dans ce comptage, pas une force supérieure : la saison et les tiges cachées ne sont pas pondérées.",
        'Wood, Fire, Earth, Metal and Water are five symbolic categories. Here the eight visible stems and branches are counted. A higher count means more occurrences, not greater strength: season and hidden stems are not weighted.'),
    'bazi_polarites': ('Yin et Yang', 'Yin and Yang',
        "Deux modes complémentaires de la tradition chinoise : réception et intériorisation pour Yin, mouvement et extériorisation pour Yang. Leur répartition vient des huit signes ; elle ne dépend ni du genre ni de la polarité choisie dans le formulaire.",
        'Two complementary modes in Chinese tradition: receptivity and inward attention for Yin, movement and outward expression for Yang. Counts come from the eight signs, not gender or the form’s reading polarity.'),
    'arbre_vie': ('Arbre de Vie', 'Tree of Life',
        "Les dix sephiroth sont des repères de la tradition kabbalistique, tels que sagesse, rigueur ou harmonie. La personnalisation proposée ici est une correspondance moderne de la date et du nom latin, réduits de 1 à 10. Elle ne prétend pas être une gématrie hébraïque ni révéler un destin imposé.",
        'The ten sephiroth are reference points in Kabbalistic tradition, such as wisdom, severity and harmony. Personalization here is a modern mapping of date and Latin-alphabet name, reduced to 1–10. It is not Hebrew gematria or an imposed destiny.'),
    'arbre_sephiroth': ('Sephiroth et correspondances', 'Sephiroth and correspondences',
        "Chaque cercle porte le nom d'une sephira. Les cercles mis en évidence correspondent à la date, au nom ou à leur combinaison selon la méthode affichée. Les lignes structurent le dessin ; elles ne sont pas des épreuves personnelles calculées.",
        'Each circle names a sephira. Highlighted circles correspond to date, name or their combination under the displayed method. Lines organize the drawing; they are not calculated personal trials.'),
    'maya_kin': ('Kin · cycle de 260 jours', 'Kin · 260-day cycle',
        "Le numéro 1 à 260 repère la combinaison du glyphe (cycle de 20 jours) et de la tonalité (cycle de 13 jours). Ici 1 Imix porte le numéro 1 et la corrélation GMT est utilisée. Cette numérotation traditionnelle est distincte du calendrier moderne Dreamspell.",
        'The number 1–260 identifies a glyph (20-day cycle) and tone (13-day cycle) combination. Here 1 Imix is number 1 and the GMT correlation is used. This traditional numbering is distinct from the modern Dreamspell calendar.'),
    'maya_tonalite': ('Tonalité du Tzolkin', 'Tzolkin tone',
        "Un nombre de 1 à 13 qui avance chaque jour en parallèle du cycle des 20 glyphes. Il décrit une place dans le cycle, pas un niveau de puissance ou une note de personnalité.",
        'A number from 1 to 13 advancing each day alongside the 20-glyph cycle. It marks a position in the cycle, not a power level or personality rating.'),
    'vedique_pada': ('Pada · quart du Nakshatra', 'Pada · Nakshatra quarter',
        "Chaque demeure lunaire de 13°20′ est divisée en quatre padas de 3°20′. Le pada précise la position de la Lune dans cette demeure. Comme le calcul est approché, un résultat près d'une frontière demande vérification.",
        'Each 13°20′ lunar mansion is divided into four 3°20′ padas. The pada refines the Moon’s position within the mansion. Since the calculation is approximate, boundary cases need verification.'),
    'vedique_ayanamsa': ('Ayanamsa · repère sidéral', 'Ayanamsa · sidereal reference',
        "Le décalage soustrait à la longitude tropicale pour obtenir une longitude sidérale. Il existe plusieurs conventions ; l'application utilise une approximation de Lahiri. C'est pourquoi un signe védique peut différer du signe occidental.",
        'The offset subtracted from tropical longitude to obtain sidereal longitude. Several conventions exist; this app uses an approximate Lahiri ayanamsa. This is why a Vedic sign may differ from a Western sign.'),
    'celte_13': ('Calendrier des 13 arbres', 'Thirteen-tree calendar',
        "Un calendrier symbolique moderne : treize périodes de 28 jours, du Bouleau au Sureau, à partir du 24 décembre. Le 23 décembre est intercalaire ; le 29 février répète le jour précédent. Il diffère du calendrier des 21 arbres et ne suit pas les lunaisons astronomiques réelles.",
        'A modern symbolic calendar: thirteen 28-day periods, from Birch to Elder, starting December 24. December 23 is intercalary; February 29 repeats the previous day. It differs from the 21-tree calendar and does not follow actual astronomical lunar months.'),
    'numerologie_nom': ('Numérologie du nom', 'Name numerology',
        "Les lettres des prénoms et du nom de famille à la naissance sont converties en nombres. Expression : toutes les lettres ; âme : voyelles ; personnalité : consonnes. Le système classique utilise A=1 à Z=26, le pythagoricien un cycle 1 à 9. Le nom affiché sert de repli si le nom de naissance manque.",
        'Given names and birth surname are converted to numbers. Expression uses all letters; soul urge uses vowels; personality uses consonants. The classical system uses A=1 through Z=26, the Pythagorean system a 1–9 cycle. Display surname is used if birth surname is absent.'),
    'numerologie_ame': ('Âme · élan spirituel', 'Soul urge',
        "Le nombre issu des voyelles des prénoms et du nom de naissance. Il sert à lire symboliquement les motivations intérieures. Ici Y est compté parmi les voyelles ; les nombres maîtres 11, 22 et 33 sont conservés.",
        'The number derived from vowels in given names and birth surname, used to read inner motivations symbolically. Here Y is counted as a vowel, and master numbers 11, 22 and 33 are preserved.'),
    'numerologie_personnalite': ('Personnalité · consonnes', 'Personality · consonants',
        "Le nombre issu des consonnes. Il évoque symboliquement la manière de se présenter et d'être perçu, tandis que l'âme concerne les motivations intérieures. Ce n'est pas un test psychométrique.",
        'The number derived from consonants. It symbolically suggests presentation and how one is perceived, while soul urge concerns inner motivations. It is not a psychometric test.'),
}
